### ISSUE TITLE
Playing notes with keyboard. 

### ISSUE THREAD

**Issue by DavidVerghese** [DavidVerghese/WebPiano#2]
Allow users to play notes by clicking keys on their keyboard. The buttons should also show the names of the keys you need to press in order to trigger the note.

**Comment by DavidVerghese** [comment]
the buttons should also show the names of the keys you need to press in order to trigger the note.

**Comment by DavidVerghese** [comment]
Each scale has an array of objects associated with it. Each object should have a property, keyStroke, that represents the key stroke needed to trigger that sound. For instance,  

`const chromatic = [
    { note: "C4", color: "white", keyStroke: "A"},
    // ... 
    }
`

**Comment by RobEgeland** [comment]
has a small bug with sound change but is implemented
